- name: Deploy Pet Clinic to Production Server
  hosts: production
  remote_user: vagrant

  tasks:
  - name: Copy JAR to Production Server
    copy:
      src: ./target/spring-petclinic-3.2.0-SNAPSHOT.jar
      dest: ./petclinic.jar

  - name: Execute JAR file
    shell: nohup java -jar petclinic.jar --server.port=8081 > output.log 2>&1 &
    args:
      executable: /bin/bash
