- name: deploy one petclinic to one server
  hosts: service
  remote_user: vagrant

  tasks:
  - name: copy the jar file to target host
    copy:
      src: ./target/spring-petclinic-2.4.2.jar
      dest: ./petclinic.jar
  - name: install openjdk11
    become: yes
    apt:
      name: openjdk-11-jre
      state: latest
      update_cache: yes
  - name: run the jar file
    shell: nohup java -jar petclinic.jar &
    args:
      executable: /bin/bash
