- name: Deploy Pet Clinic to Production Server
  hosts: production
  become: yes

  tasks:
  - name: Install OpenJDK 17
    apt:
      name: openjdk-17-jdk
      state: present
      update_cache: yes

  - name: Copy JAR to Production Server
    copy:
      src: ./target/spring-petclinic-3.2.0-SNAPSHOT.jar
      dest: ./petclinic.jar
      owner: vagrant
      group: vagrant
    delegate_to: 192.168.50.11

  - name: Execute JAR file
    shell: nohup java -jar petclinic.jar --server.port=8081
    args:
      executable: /bin/bash
